# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ng2-recaptcha
email: dethariel@gmail.com
description: "Angular 2 + TypeScript component for Google reCAPTCHA"
baseurl: "/ng2-recaptcha" # the subpath of your site, e.g. /blog
github_username: "dethariel"
devsuffix: ""

# SystemJS mapping for ng2-recaptcha component
recaptchaMapping: "https://npmcdn.com/ng2-recaptcha@1.0.0" # stick to a particular version to avoid caching confusion
# Uncomment to debug (you must run `cd examples && npm install` in order for that to work)
#recaptchaMapping: "./examples/node_modules/ng2-recaptcha" # always fetch the latest npm version for production

# Build settings
markdown: kramdown
